import Lean.Meta
import LeanAide.Responses
import LeanAide.PaperCodes
import LeanAide.Codegen
import LeanAideCore.Translate
import Mathlib

open Lean LeanAide

set_option maxHeartbeats 10000000
set_option maxRecDepth 1000
set_option compiler.extract_closed false

def usage : String :=
  "Usage: lake env lean --run codegen.lean <structured-json-file>"

def stripJsonSuffix (name : String) : String :=
  if name.endsWith ".json" then
    (name.dropEnd ".json".length).toString
  else
    name

def outputPathFor (inputPath : System.FilePath) : System.FilePath :=
  let inputName := inputPath.fileName.getD "generated.json"
  let stem := stripJsonSuffix inputName
  System.mkFilePath ["CodeGen", stem ++ ".lean"]

def taskJson (js : Json) : Json :=
  match js.getObjVal? "document_json" with
  | Except.ok _ => js
  | Except.error _ => Json.mkObj [("document_json", js)]

def ensureMathlibImport (topCode : String) : String :=
  if topCode.contains "import Mathlib" then
    topCode
  else
    "import Mathlib\n" ++ topCode

def generatedFileContents (inputPath : System.FilePath) (topCode documentCode : String) : String :=
  let topCode := ensureMathlibImport topCode
  s!"{topCode.trimAsciiEnd}\n\n-- Generated by codegen.lean from {inputPath}\n\n{documentCode.trimAsciiEnd}\n"

def runCodegen (inputPath : System.FilePath) : IO UInt32 := do
  initSearchPath (← findSysroot)
  let raw ← IO.FS.readFile inputPath
  let js ←
    match Json.parse raw with
    | Except.ok js => pure js
    | Except.error err => do
      IO.eprintln s!"Failed to parse JSON from {inputPath}: {err}"
      return 1
  let env ←
    importModules (loadExts := true) #[
      {module := `Mathlib},
      {module := `LeanAideCore.Translate},
      {module := `LeanAide.PaperCodes},
      {module := `LeanAide.Responses},
      {module := `LeanAide.Codegen}] {}
  let ctx : Core.Context :=
    { fileName := inputPath.toString
      fileMap := {source := raw, positions := #[]}
      maxHeartbeats := 0
      maxRecDepth := 1000000 }
  let translator : Translator := {}
  let core := leanFromStructuredJsonTask (taskJson js) translator |>.runToCore
  let result ← core.run' ctx {env := env} |>.runToIO'
  match result.getObjValAs? String "result" with
  | Except.ok "success" =>
      let documentCode ←
        match result.getObjValAs? String "document_code" with
        | Except.ok code => pure code
        | Except.error err => do
          IO.eprintln s!"Code generation succeeded but no document_code was returned: {err}"
          return 1
      let topCode := result.getObjValAs? String "top_code" |>.toOption.getD "import Mathlib\n"
      let outFile := outputPathFor inputPath
      IO.FS.createDirAll (System.mkFilePath ["CodeGen"])
      IO.FS.writeFile outFile (generatedFileContents inputPath topCode documentCode)
      IO.println s!"Generated {outFile}"
      match result.getObjVal? "declarations" with
      | Except.ok decls => IO.println s!"Declarations: {decls.compress}"
      | Except.error _ => pure ()
      return 0
  | Except.ok other => do
      IO.eprintln s!"Code generation returned non-success result: {other}"
      IO.eprintln result.pretty
      return 1
  | Except.error err => do
      IO.eprintln s!"Code generation returned malformed response: {err}"
      IO.eprintln result.pretty
      return 1

unsafe def main (args : List String) : IO UInt32 := do
  match args with
  | [input] => runCodegen input
  | _ => do
      IO.eprintln usage
      return 1
