# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-04-26T10:19:42+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


# Shared metadata and references


class Metadata(BaseModel):
    authors: Optional[List[str]] = Field(
        None, description='(OPTIONAL) List of authors of the document.'
    )
    date: Optional[date_aliased] = Field(
        None, description='(OPTIONAL) Date of the document.'
    )


class TheoremHeader(Enum):
    Theorem = 'Theorem'
    Lemma = 'Lemma'
    Proposition = 'Proposition'
    Corollary = 'Corollary'
    Claim = 'Claim'


class DefinitionHeader(Enum):
    Definition = 'Definition'
    Notation = 'Notation'
    Terminology = 'Terminology'
    Convention = 'Convention'


class CalculationStep(RootModel):
    root: str = Field(
        ...,
        description='A step, typically an equality or inequality, in a calculation or computation. Write the step fully: e.g. in the sequence `a=b\n=c`, write `a=b` and `b=c` as two separate steps and DO NOT OMIT `b` in the second step.',
    )


class ResultUsed(BaseModel):
    model_config = ConfigDict(extra='forbid')

    statement: str = Field(..., description='The statement of the result used.')
    target_identifier: Optional[str] = Field(
        None,
        description="(OPTIONAL) The unique 'label' of the document element being referenced (e.g., 'sec:intro', 'thm:main', 'fig:,diagram').",
    )
    mathlib_identifier: Optional[str] = Field(
        None,
        description='(OPTIONAL) The name of the result being used in Lean Prover or its library Mathlib).',
    )


class BibliographyEntry(BaseModel):
    model_config = ConfigDict(extra='forbid')

    key: str = Field(
        ..., description="Unique key used for citations (e.g., 'Knuth1974', '[1]')."
    )
    formatted_entry: str = Field(
        ...,
        description='The full bibliographic reference, formatted as text (e.g., APA, BibTeX style).',
    )


class Citation(BaseModel):
    model_config = ConfigDict(extra='forbid')

    cite_keys: List[str] = Field(
        ..., description='An array of bibliography keys being cited.', min_length=1
    )


class InternalReference(BaseModel):
    model_config = ConfigDict(extra='forbid')

    target_identifier: str = Field(
        ...,
        description="The unique 'label' of the document element being referenced (e.g., 'sec:intro', 'thm:main', 'fig:diagram').",
    )


# Atomic logical steps


class LetStatement(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['let_statement'] = Field(
        'let_statement', description='The type of this logical step.'
    )
    variable_name: str = Field(
        ...,
        description='The variable being defined (use `<anonymous>` if there is no name such as in `We have a group structure on S`)',
    )
    value: Optional[str] = Field(
        None,
        description='(OPTIONAL) The value of the variable being defined. This MUST BE an explicit value. If the value is the obtained from an existence statement, use `assert_statement` instead.',
    )
    variable_type: Optional[str] = Field(
        None,
        description='(OPTIONAL) The type of the variable, such as `real number`, `function from S to T`, `element of G` etc.',
    )
    properties: Optional[str] = Field(
        None,
        description='(OPTIONAL) Specific properties of the variable beyond the type',
    )
    statement: Optional[str] = Field(None, description='The full statement made.')


class SomeStatement(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['some_statement'] = Field(
        'some_statement', description='The type of this logical step.'
    )
    variable_name: str = Field(
        ...,
        description='The variable being defined (use `<anonymous>` if there is no name such as in `We have a group structure on S`)',
    )
    variable_kind: Optional[str] = Field(
        None,
        description='(OPTIONAL) The type of the variable, such as `real number`, `function from S to T`, `element of G` etc.',
    )
    properties: Optional[str] = Field(
        None,
        description='(OPTIONAL) Specific properties of the variable beyond the type',
    )
    statement: Optional[str] = Field(None, description='The full statement made.')


class AssumeStatement(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['assume_statement'] = Field(
        'assume_statement', description='The type of this logical step.'
    )
    assumption: str = Field(..., description='The assumption text.')
    label: Optional[str] = Field(
        None, description='(OPTIONAL) The label of the assumption, if any.'
    )
    citations: Optional[List[Citation]] = Field(
        None,
        description='(OPTIONAL) Citations supporting or related to the assumption.',
    )
    internal_references: Optional[List[InternalReference]] = Field(
        None, description='(OPTIONAL) Internal references related to the assumption.'
    )


class Calculation(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['calculation'] = Field(
        'calculation', description='The type of this logical step.'
    )
    inline_calculation: Optional[str] = Field(
        None,
        description='A simple calculation or computation written as a single line.',
    )
    calculation_sequence: Optional[List[CalculationStep]] = Field(
        None, description='A list of elements of type `calculation_step`.'
    )


class AssertStatement(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['assert_statement'] = Field(
        'assert_statement', description='The type of this logical step.'
    )
    claim: str = Field(
        ...,
        description='The mathematical claim being asserted, NOT INCLUDING proofs, justifications or results used. The claim should be purely a logical statement which is the *consequence* obtained.',
    )
    proof_method: Optional[str] = Field(
        None,
        description='(OPTIONAL) The method used to prove the claim. This could be a direct proof, proof by contradiction, proof by induction, etc. this should be a single phrase or a fairly simple sentence; if a longer justification is needed break the step into smaller steps. If the method is deduction from a result, use `citations`or `internal_references`.',
    )
    label: Optional[str] = Field(
        None,
        description='The label of the statement, if any. If this statement is used in a proof or as justification for an assertion, it should be labeled so that it can be referenced later.',
    )
    citations: Optional[List[Citation]] = Field(
        None,
        description='(OPTIONAL) Explicit list of citations relevant to this theorem statement.',
    )
    results_used: Optional[List[ResultUsed]] = Field(
        None,
        description='(OPTIONAL) Explicit list of results used in the proof, for example where the assertion says "using ...". Include both standard results and results from the document itself, with references where available.',
    )
    internal_references: Optional[List[InternalReference]] = Field(
        None,
        description='(OPTIONAL) Explicit list of internal references mentioned in the theorem statement.',
    )
    calculation: Optional[Calculation] = Field(
        None, description='(OPTIONAL) An equation, inequality, short calculation etc.'
    )


class ConcludeStatement(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['conclude_statement'] = Field(
        'conclude_statement', description='The type of this logical step.'
    )
    claim: Optional[str] = Field(
        None,
        description='(OPTIONAL) conclusion of the proof.This is typically the final statement of a proof giving the conclusion of the theorem. If this is not given, it is assumed to be the claim of the theorem being proved.',
    )
    results_used: Optional[List[ResultUsed]] = Field(
        None,
        description='(OPTIONAL) Explicit list of results used in the proof, for example where the assertion says "using ...". Include both standard results and results from the document itself, with references where available.',
    )


class ContradictionStatement(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['contradiction_statement'] = Field(
        'contradiction_statement',
        description='The type of this logical step.',
    )
    assumption: str = Field(
        ..., description='The assumption being made to be contradicted.'
    )
    proof: ProofDetails = Field(
        ..., description='The proof of the contradiction given the assumption.'
    )


class HypothesisStatement(RootModel):
    root: Union[LetStatement, AssumeStatement, SomeStatement]


# Proof case payloads


class PatternCase(BaseModel):
    model_config = ConfigDict(extra='forbid')

    pattern: str = Field(..., description='The pattern determining this case.')
    proof: ProofDetails = Field(..., description='Proof of this case.')


class ConditionCase(BaseModel):
    model_config = ConfigDict(extra='forbid')

    condition: str = Field(..., description='The condition determining this case.')
    proof: ProofDetails = Field(..., description='Proof for this case.')


class InductionCase(BaseModel):
    model_config = ConfigDict(extra='forbid')

    condition: str = Field(..., description='The condition determining this case.')
    induction_hypotheses: Optional[List[str]] = Field(
        None,
        description='(OPTIONAL) The induction hypotheses. Give the full assumption for the case. Omit for base cases.',
    )
    proof: ProofDetails = Field(..., description='Proof for this case.')


# Composite proof structures


class PatternCasesProof(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['pattern_cases_proof'] = Field(
        'pattern_cases_proof', description='The type of this logical step.'
    )
    on: str = Field(
        ...,
        description='The variable or expression which is being matched against patterns.',
    )
    proof_cases: List[PatternCase] = Field(
        ..., description='A list of elements of type `case`.'
    )


class BiImplicationCasesProof(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['bi-implication_cases_proof'] = Field(
        'bi-implication_cases_proof',
        description='The type of this logical step.',
    )
    if_proof: ProofDetails = Field(..., description='Proof that `P` implies `Q`.')
    only_if_proof: ProofDetails = Field(..., description='Proof that `Q` implies `P`.')


class ConditionCasesProof(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['condition_cases_proof'] = Field(
        'condition_cases_proof',
        description='The type of this logical step.',
    )
    condition: str = Field(
        ..., description='The condition based on which the proof is split.'
    )
    true_case_proof: ProofDetails = Field(
        ..., description='Proof of the case where the condition is true.'
    )
    false_case_proof: ProofDetails = Field(
        ..., description='Proof of the case where the condition is false.'
    )


class MultiConditionCasesProof(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['multi-condition_cases_proof'] = Field(
        'multi-condition_cases_proof',
        description='The type of this logical step.',
    )
    proof_cases: List[ConditionCase] = Field(
        ..., description='The conditions and proofs in the different cases.'
    )
    exhaustiveness: Optional[ProofDetails] = Field(
        None, description='(OPTIONAL) Proof that the cases are exhaustive.'
    )


class GeneralInductionProof(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['general_induction_proof'] = Field(
        'general_induction_proof',
        description='The type of this logical step.',
    )
    induction_principle: str = Field(
        ...,
        description="The induction principle being used, such as 'strong induction for natural numbers' or 'structural induction for binary trees'.",
    )
    proof_cases: List[InductionCase] = Field(
        ..., description='The conditions and proofs in the different cases.'
    )


class InductionProof(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['induction_proof'] = Field(
        'induction_proof', description='The type of this logical step.'
    )
    on: str = Field(
        ..., description='The variable or expression on which induction is being done.'
    )
    prev_var: Optional[str] = Field(
        None,
        description="(OPTIONAL) The variable `m` so that the induction case if `m + 1`. If omitted it is assumed that it is the same as the 'on' variable, i.e., the induction step is `n + 1` where `n` is the variable on which induction is done.",
    )
    base_case_proof: ProofDetails = Field(..., description='Proof of the base case.')
    induction_step_proof: ProofDetails = Field(
        ...,
        description='Proof of the induction step, which typically shows that if the statement holds for `n`, it holds for `n+1`.',
    )


class LogicalStepSequence(RootModel):
    root: List[LogicalStep] = Field(
        ...,
        description="A sequence of structured logical steps, typically used within a proof or derivation, consisting of statements like 'let', 'assert', 'assume', etc.",
    )


class ProofDetails(RootModel):
    root: Union[
        LogicalStepSequence,
        PatternCasesProof,
        BiImplicationCasesProof,
        ConditionCasesProof,
        MultiConditionCasesProof,
        InductionProof,
        GeneralInductionProof,
    ]


class Proof(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['Proof'] = Field(
        'Proof', description='The type of this document element.'
    )
    claim_label: str = Field(..., description='Theorem label being proved.')
    proof_steps: ProofDetails


# Document elements


class Definition(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['Definition'] = Field(
        'Definition', description='The type of this document element.'
    )
    definition: str = Field(..., description='Definition content.')
    name: str = Field(
        ...,
        description='The name of the defined object, concept or property. This should be a single word and appear in the definition text.',
    )
    label: str = Field(..., description='Definition identifier.')
    header: DefinitionHeader = Field(..., description='The definition type.')
    citations: Optional[List[Citation]] = Field(
        None,
        description='(OPTIONAL) Explicit list of citations relevant to this theorem statement.',
    )
    internal_references: Optional[List[InternalReference]] = Field(
        None,
        description='(OPTIONAL) Explicit list of internal references mentioned in the theorem statement.',
    )


class Paragraph(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['Paragraph'] = Field(
        'Paragraph', description='The type of this document element.'
    )
    text: str = Field(
        ...,
        description="The main text content of the paragraph. Inline citations (e.g., [1], [Knuth74]) and internal references (e.g., see Section 2, Theorem 3) might be embedded within this string or explicitly listed in 'citations'/'internal_references'.",
    )
    citations: Optional[List[Citation]] = Field(
        None,
        description='(OPTIONAL) Explicit list of citations mentioned in this paragraph.',
    )
    internal_references: Optional[List[InternalReference]] = Field(
        None,
        description='(OPTIONAL) Explicit list of internal references mentioned in this paragraph.',
    )


class Figure(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['Figure'] = Field(
        'Figure', description='The type of this document element.'
    )
    label: str = Field(
        ...,
        description="Unique identifier/label for referencing (e.g., 'fig:flowchart').",
    )
    source: str = Field(..., description='URL or path to the image file.')
    caption: Optional[str] = Field(
        None, description='(OPTIONAL) Caption describing the figure.'
    )
    alt_text: Optional[str] = Field(
        None, description='(OPTIONAL) Alternative text for accessibility.'
    )


class Table(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['Table'] = Field(
        'Table', description='The type of this document element.'
    )
    label: str = Field(
        ...,
        description="Unique identifier/label for referencing (e.g., 'tab:results').",
    )
    caption: Optional[str] = Field(
        None, description='(OPTIONAL) Caption describing the table.'
    )
    content: List[List[str]] = Field(
        ...,
        description='Table data, represented as an array of rows, where each row is an array of cell strings.',
    )
    header_row: Optional[bool] = Field(
        False,
        description="(OPTIONAL) Indicates if the first row in 'content' is a header row. Default: false",
    )


class Bibliography(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['Bibliography'] = Field(
        'Bibliography', description='The type of this document element.'
    )
    header: str = Field(
        ..., description="The section header (e.g., 'References', 'Bibliography')."
    )
    entries: List[BibliographyEntry] = Field(
        ..., description='List of bibliography entries.'
    )


class Section(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['Section'] = Field(
        'Section', description='The type of this document element.'
    )
    content: LogicalStepSequence
    label: str = Field(..., description='Section identifier.')
    level: Optional[int] = Field(
        None,
        description='The section level such as `1` for a section, `2` for a subsection.',
    )
    header: str = Field(..., description='The section header.')


class Theorem(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['Theorem'] = Field(
        'Theorem', description='The type of this document element.'
    )
    hypothesis: Optional[List[HypothesisStatement]] = Field(
        None,
        description="(OPTIONAL) The hypothesis or assumptions of the theorem, consisting of statements like 'let', 'assume', etc.",
    )
    claim: str = Field(..., description='The statement.')
    label: str = Field(
        ...,
        description="Unique identifier/label for referencing (e.g., 'thm:main', 'lem:pumping').",
    )
    proof: Optional[ProofDetails] = Field(
        None,
        description='Proof of the theorems, if it is present soon after the statement.',
    )
    header: TheoremHeader = Field(
        ...,
        description='The type of theorem-like environment. Must be one of the predefined values.',
    )
    citations: Optional[List[Citation]] = Field(
        None,
        description='(OPTIONAL) Explicit list of citations relevant to this statement.',
    )
    internal_references: Optional[List[InternalReference]] = Field(
        None,
        description='(OPTIONAL) Explicit list of internal references mentioned in the statement.',
    )


class LogicalStep(RootModel):
    root: Union[
        Theorem,
        Definition,
        LetStatement,
        AssertStatement,
        AssumeStatement,
        SomeStatement,
        PatternCasesProof,
        BiImplicationCasesProof,
        ConditionCasesProof,
        MultiConditionCasesProof,
        InductionProof,
        GeneralInductionProof,
        Calculation,
        ContradictionStatement,
        ConcludeStatement,
        Section,
        Proof,
        Paragraph,
        Figure,
        Table,
        Bibliography,
    ]


class Document(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['document'] = Field(
        'document', description='The type of this document element.'
    )
    body: LogicalStepSequence
    title: Optional[str] = Field(
        None, description='(OPTIONAL) The title of the document.'
    )
    abstract: Optional[str] = Field(
        None, description='(OPTIONAL) The abstract of the document.'
    )
    metadata: Optional[Metadata] = Field(
        None,
        description='(OPTIONAL) Metadata about the document, such as authors, date, etc.',
    )


class DocumentContainer(BaseModel):
    model_config = ConfigDict(extra='forbid')

    document: Document = Field(
        ...,
        description='A simple wrapper containing a single `document` key holding a `Document` object.',
    )


# Document orchestrator schema


class OrchestratorParagraphKind(Enum):
    prose = 'prose'
    mathematical_prose = 'mathematical_prose'


class OrchestratorElement(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal[
        'section',
        'theorem',
        'definition',
        'remark',
        'paragraph',
        'figure',
        'table',
    ] = Field(
        ...,
        description="The element type. One of 'section','theorem','definition','remark','paragraph','figure','table'.",
    )
    header: Optional[str] = Field(
        None, description="Optional header text (e.g., 'Theorem 1.1', 'Section 2')."
    )
    label: Optional[str] = Field(
        None, description="Optional unique identifier for the element."
    )
    content_kind: Optional[OrchestratorParagraphKind] = Field(
        None,
        description=(
            "For paragraph-like or remark-like blocks, distinguishes ordinary prose "
            "from mathematically substantive prose. Use `prose` for explanatory text "
            "with little or no symbolic content, and `mathematical_prose` for "
            "paragraphs that carry mathematical definitions, claims, derivations, or "
            "dense inline/display notation."
        ),
    )
    contains_display_math: Optional[bool] = Field(
        None,
        description=(
            "Whether the block contains displayed mathematics such as aligned equations, "
            "display formulas, or other standalone math environments."
        ),
    )
    raw_source: str = Field(
        ..., description="The raw text of this block to be passed to the next agent."
    )


class DocumentOrchestrator(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Literal['document'] = Field(
        'document', description="Constant value: 'document'."
    )
    title: Optional[str] = Field(None, description='(OPTIONAL) The title of the document.')
    abstract: Optional[str] = Field(
        None, description='(OPTIONAL) The abstract of the document.'
    )
    elements: List[OrchestratorElement] = Field(
        ..., description='Ordered list of structural elements contained in the document.'
    )


for model_type in (
    HypothesisStatement,
    PatternCase,
    ConditionCase,
    InductionCase,
    PatternCasesProof,
    BiImplicationCasesProof,
    ConditionCasesProof,
    MultiConditionCasesProof,
    GeneralInductionProof,
    InductionProof,
    ContradictionStatement,
    LogicalStepSequence,
    ProofDetails,
    Proof,
    Section,
    Theorem,
    LogicalStep,
    Document,
    DocumentContainer,
    OrchestratorElement,
    DocumentOrchestrator,
):
    model_type.model_rebuild()
