import Mathlib
universe u v w u_1 u_2 u_3 u_4 u_5 u_6 u_7 u_8 u_9 u_10 u₁ u₂ u₃
set_option maxHeartbeats 10000000
set_option linter.unreachableTactic false
open scoped Nat

-- Generated by codegen.lean from mathdoc_agent/examples/even_induction_cases.json

theorem Nat.even_or_even_succ : ∀ (n : ℕ), Even n ∨ Even (n + (1 : ℕ)) :=
    by
    intro n
    induction n with
    | zero => simp only [Even.zero, zero_add, Nat.not_even_one, or_false]
    | succ n
      ih =>
      if condition_16468389163427038829 : Even n then grind only [= Nat.even_iff]
      else if condition_3270161773976375427 : Even (n + (1 : ℕ)) then grind only else grind only
      done
    done
