import Mathlib
universe u v w u_1 u_2 u_3 u_4 u_5 u_6 u_7 u_8 u_9 u_10 u₁ u₂ u₃
set_option maxHeartbeats 10000000
set_option linter.unreachableTactic false
open scoped Nat

-- Generated by codegen.lean from mathdoc_agent/examples/even_induction_cases.json

theorem Nat.even_or_even_succ : ∀ (n : ℕ), Even n ∨ Even (n + (1 : ℕ)) :=
    by
    intro n
    induction n with
    | zero =>
      have assert_14506765972283818572 : ∀ (n : ℕ), Even (0 : ℕ) ∨ Even ((0 : ℕ) + (1 : ℕ)) := by
        simp only [Even.zero, zero_add, Nat.not_even_one, or_false, implies_true]
      grind
    | succ n
      ih =>
      if condition_16468389163427038829 : Even n then
        have assert_3690336956872712118 : Even (n + (1 : ℕ)) ∨ Even (n + (2 : ℕ)) := by grind only [= Nat.even_iff]
        grind -- manual fix
      else
        if condition_3270161773976375427 : Even (n + (1 : ℕ)) then
          have assert_3690336956872712118 : Even (n + (1 : ℕ)) ∨ Even (n + (2 : ℕ)) := by grind only
          grind -- manual fix
        else grind only
      done
    done
